### ISSUE TITLE
Markov.PerformTransientMarkovAnalysisThread is not working?

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#513]
iBioSim Version 3.0.0-beta

Operating system: Mac OS X

Bug reported by: zhen.zhang@usu.edu

Description:
This occured when performing state-based analysis on dual_feedback_oscillaotr. I will attach screenshots.

Stack trace:
java.lang.NullPointerException
	at edu.utah.ece.async.ibiosim.analysis.markov.PerformTransientMarkovAnalysisThread.start(PerformTransientMarkovAnalysisThread.java:53)
	at edu.utah.ece.async.ibiosim.analysis.Run.executeMarkov(Run.java:413)
	at edu.utah.ece.async.ibiosim.analysis.Run.execute(Run.java:157)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisView.run(AnalysisView.java:903)
	at edu.utah.ece.async.ibiosim.gui.analysisView.AnalysisThread.run(AnalysisThread.java:43)

**Comment by zgzn** [comment]
See attached zip file. I also attached two screenshots. 
<img width="1033" alt="screen shot 2018-03-30 at 9 08 23 pm" src="https://user-images.githubusercontent.com/7920249/38159165-169a062a-3460-11e8-9c20-661418a96960.png">
<img width="1037" alt="screen shot 2018-03-30 at 9 08 55 pm" src="https://user-images.githubusercontent.com/7920249/38159166-16affbd8-3460-11e8-97fb-9a57ae26c23b.png">
[stochastic_model_checking.zip](https://github.com/MyersResearchGroup/iBioSim/files/1865139/stochastic_model_checking.zip)

**Comment by cjmyers** [comment]
This should be fixed now.  Same bug with progress bar object being null.

@leandrohw transient analysis can set meaningful progress.  Can we make sure that the markov analyzers get the progress bar passed to them?

**Comment by zgzn** [comment]
Exceptions disappeared. But the TSD Graph could not get any data to plot. I remember it used to be able to show two bars showing the probabilities for success and failure. I did not find any results printed in terminal either.

**Comment by cjmyers** [comment]
This method in StateGraph.java I believe output these results.  

	public boolean outputTSD(String filename) {
		if (probData != null) {
			probData.outputTSD(filename);
			return true;
		}
		return false;
	}

This method is no longer called anywhere.

@leandrohw did you perhaps lose the call to this method in your refactor?  Or is there some other way these should be printed.

**Comment by cjmyers** [comment]
@zgzn should be fixed now, please test.

**Comment by zgzn** [comment]
I am still having issues with displaying the results on the TSD graph. It does not have data to graph.

**Comment by cjmyers** [comment]
Please send the project you are testing with.

**Comment by zgzn** [comment]
The "toggle_switch" analysis view in the attached project. 

[stochastic_model_checking.zip](https://github.com/MyersResearchGroup/iBioSim/files/1885868/stochastic_model_checking.zip)

**Comment by cjmyers** [comment]
Ok, I think I found the issue.  There is no property being passed to the transient analysis method.  There used to be a pop-up that would ask you to select the transient property that you wanted to check.  However, this has vanished in the refactor.  @leandrohw any idea how to resurrect this?

**Comment by cjmyers** [comment]
https://github.com/MyersResearchGroup/iBioSim/blob/b3a635b7076f3ace5b2db73cb4daf39642f39b14/gui/src/main/java/edu/utah/ece/async/ibiosim/gui/analysisView/Run.java

See line 637

@leandrohw any idea where this ended up?

**Comment by cjmyers** [comment]
@zgzn : I checked in a temporary fix for this issue.  There should be a pop-up to allow you to select the constraint to use during transient analysis.  Now, instead it just uses the first one it finds that starts with an F, G, or U.  To make this work, you will need to deselect any constraints in the schematic that you do not want analyzed.  In future, we will restore the pop-up, or alternatively provide an error message if you have too many transient constraints.

**Comment by cjmyers** [comment]
@zgzn can you confirm this is fixed?

**Comment by zgzn** [comment]
This is fixed.
